name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10, 12 ]
        os: [ ubuntu-18.04, windows-latest ]
    env:
      FORCE_COLOR: 1
    name: ${{ matrix.os }} - node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt install -y supervisor
          sudo yarn global add ghost-cli
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test:e2e
